#!/bin/bash

mkdir logs


#!/bin/bash
#echo "Starting cassandra"

#cd $CASSANDRA_HOME 
#mkdir logs
#mkdir data

#solving the nightmare
#setting min (-Xms) and max (-Xmx) heap sizes to
echo "-Xms1G" >> /etc/cassandra/jvm.options
echo "-Xmx2G" >> /etc/cassandra/jvm.options

chmod +x  ${HOME}/bin/cassandra
nohup ${HOME}/bin/cassandra &> ~/logs/cassandra.log &
#had to edit the script to avoid user id problems. See the commented lines
#cp ~/resources/configs/cassandra/cassandra $CASSANDRA_HOME/bin/
#chmod +x  $CASSANDRA_HOME/bin/cassandra

#nohup  ./bin/cassandra  &> ~/logs/cassandra-$CASSANDRA_VERSION.log &

#while ! cqlsh -e 'describe cluster' ; do
#    echo "Waiting for Cassandra cluster"
#    sleep 1
#done

nohup mongod --replSet rs0 --dbpath ${HOME}/data/db &> ~/logs/mongodb.log &

sleep 10

exec "$@"
